name: Nightvision
version: ${project.version}
main: me.mates.nightvision.Nightvision
api-version: 1.16
authors: [ mates ]
description: toggle night vision
commands:
  nightvision:
    description: dรก ti nightvision
    aliases: [nv]